crds:
  install: false

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  insecure: true
  ingress:
    enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicaCount: 1