apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: fritz-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.181-192.168.178.199
  - fd00:ec2::/48
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
