apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto
  namespace: argocd
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: konvoi
  source:
    path: konvoi/resources/emojivoto
    repoURL: https://github.com/christianhuening/pinetes.git
