apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: konvoi
  source:
    chart: linkerd-crds
    repoURL: https://github.com/christianhuening/pinetes.git
    targetRevision: 1.0.0
    helm:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
